### ISSUE TITLE
Timepicker not working with bootstrap modal.

### ISSUE THREAD

**Issue by InsaneSkull** [janisto/yii2-timepicker#1]
When using with modal and both date and time mode is enabled timepicket doesn't opening. I am working with Mozila Firefox.

**Comment by janisto** [comment]
I think that's due to the z-index values.

Try this CSS:

```
    #ui-datepicker-div {
        z-index: 3000 !important;
    }
```

**Comment by janisto** [comment]
You should also report this bug to:
https://github.com/trentrichardson/jQuery-Timepicker-Addon

**Comment by InsaneSkull** [comment]
It works..but partially. I am unable to set position of timepicker. It covers the whole modal.

**Comment by janisto** [comment]
You should add the timepicker inside an element that has proper width or change the css related to timepicker.

**Comment by InsaneSkull** [comment]
I want to change the size of timepicker.

**Comment by janisto** [comment]
Do you mean the input field width?

**Comment by InsaneSkull** [comment]
Nope..only timepicker size.

**Comment by janisto** [comment]
Then you should override the CSS styles from jqueryui-timepicker-addon and jquery ui.

**Comment by InsaneSkull** [comment]
Ok..got it. Thanks for your help and advice.
